### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by l1dge** [PyBites-Open-Source/pybites-alarm#8]
Hi Bob,
This didn't work on Windows out of the box. You need to install the Visual Studio build tools and FFmpeg for it to build and run correctly from a Windows 10 command prompt, but once that's done it works great albeit without being able to background the process. I haven't been able to get it to work in WSL2 yet either but I think this is more a WSL2 hardware issue than python. 

Cheers
Lee

**Comment by bbelderbos** [comment]
Great, thanks for testing I will add this to the README

**Comment by bbelderbos** [comment]
Readme updated, thanks again.
