### ISSUE TITLE
Background process not working on Windows 10

### ISSUE THREAD

**Issue by l1dge** [PyBites-Open-Source/pybites-alarm#9]
Hi Bob,
The -b option to background the alarm process doesn't appear to work on Windows. I've tried in command prompt and powershell. Might be worth removing that option for the Windows platform unless you can find a workaround.

Cheers
Lee

**Comment by bbelderbos** [comment]
Addressed in https://github.com/PyBites-Open-Source/pybites-alarm/pull/10 = 0.0.5
